# Generated by Django 4.2.6 on 2023-12-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macrobulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True)),
                ('macro_economic_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macrobulletin.economicindex')),
            ],
        ),
    ]
